# Generated by Django 5.1.7 on 2025-04-01 01:46

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to=students.models.face_image_upload_path)),
            ],
        ),
    ]
