# Generated by Django 5.1.7 on 2025-04-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='hi', max_length=128),
        ),
    ]
