# Generated by Django 5.1.7 on 2025-04-01 13:48

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('no_of_pages', models.IntegerField()),
                ('no_of_books', models.IntegerField()),
                ('book_image', models.ImageField(upload_to=students.models.book_image_upload_path)),
            ],
        ),
    ]
