# Generated by Django 5.2 on 2025-04-09 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.user'),
        ),
    ]
